const ADD_ITEM = 'ADD_ITEM';
const ADD_TEXT = 'ADD_TEXT';
const CHANGE_FILTER = 'CHANGE_FILTER';
const DELETE_ITEM = 'DELETE_ITEM';
const GET_SAVED_ITEMS = 'GET_SAVED_ITEMS';
const SEARCH_ITEM = 'SEARCH_ITEM';
const UPDATE_ITEMS = 'UPDATE_ITEMS';

export {ADD_ITEM, ADD_TEXT, CHANGE_FILTER, DELETE_ITEM, GET_SAVED_ITEMS,
        SEARCH_ITEM, UPDATE_ITEMS}